CREATE TABLE fact_spells (
	spell_id INT IDENTITY(1,1) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	level TINYINT NOT NULL,
	school_ID INT NOT NULL,
	action_type VARCHAR(255) NOT NULL,
	is_concentration BIT NOT NULL,
	is_ritual BIT NOT NULL,
	casting_time VARCHAR(255),
	range VARCHAR(255) NOT NULL,
	require_visual_component BIT NOT NULL,
	require_somatic_component BIT NOT NULL,
	require_material_component BIT NOT NULL,
	duration VARCHAR(255) NOT NULL,
	description VARCHAR(MAX) NOT NULL,
	materials VARCHAR(MAX),
	cantrip_upgrade VARCHAR(MAX),
	higher_level_slot VARCHAR(MAX),
	material_cost INT NOT NULL,
	does_spell_consume BIT NOT NULL,
	saving_throw_type VARCHAR(255),
	is_half_damage_on_success BIT NOT NULL,
	does_damage BIT NOT NULL,
	is_exclusive BIT NOT NULL
)